CREATE TABLE IF NOT EXISTS `#__xgallery` (
  `id` int(11) NOT NULL auto_increment,
  `cid` int(11) NOT NULL default '0',
  `name` varchar(255) NOT NULL,
  `folder` text,
  `thumb` text,
  `hits` int(11) NOT NULL default '0',
  `banner` text,
  `quicktake` text NOT NULL,
  `description` text NOT NULL,
  `lft` int(11) NOT NULL default '0',
  `rgt` int(11) NOT NULL default '0',
  `access` int(11) unsigned NOT NULL default '0',
  `groupname` varchar(255) NOT NULL default 'Public',
  `creation_date` datetime NOT NULL,
  `published` tinyint(1) NOT NULL default 0,
  `ordering` int(11), 
  `metakey` text NOT NULL,
  `metadesc` text NOT NULL,
  `metaauthor` text NOT NULL,
  `metarobots` text NOT NULL,
  PRIMARY KEY  (`id`)
);

CREATE TABLE IF NOT EXISTS `#__xgallery_categories` (
  `id` int(11) NOT NULL auto_increment,
  `pid` int(11) NOT NULL default '0',
  `name` varchar(255) NOT NULL,
  `thumb` text,
  `hits` int(11) NOT NULL default '0',
  `banner` text,
  `quicktake` text NOT NULL,
  `description` text NOT NULL,
  `lft` int(11) NOT NULL default '0',
  `rgt` int(11) NOT NULL default '0',
  `access` int(11) unsigned NOT NULL default '0',
  `groupname` varchar(255) NOT NULL default 'Public',
  `creation_date` datetime NOT NULL,
  `published` tinyint(1) NOT NULL default 0,
  `ordering` int(11),
  `metakey` text NOT NULL,
  `metadesc` text NOT NULL,
  `metaauthor` text NOT NULL,
  `metarobots` text NOT NULL,
  PRIMARY KEY  (`id`)
);

CREATE TABLE IF NOT EXISTS `#__xgallery_tmp` (
  `id_tmp` int(11) NOT NULL auto_increment,
  `id` int(11) NOT NULL default '0',
  `cid` int(11) NOT NULL default '0',
  `name` varchar(255) NOT NULL,
  `folder` text,
  `thumb` text,
  `hits` int(11) NOT NULL default '0',
  `banner` text,
  `quicktake` text NOT NULL,
  `description` text NOT NULL,
  `lft` int(11) NOT NULL default '0',
  `rgt` int(11) NOT NULL default '0',
  `access` int(11) unsigned NOT NULL default '0',
  `groupname` varchar(255) NOT NULL default 'Public',
  `creation_date` datetime NOT NULL,
  `creation_date_tmp` datetime NOT NULL,
  `published` tinyint(1) NOT NULL default 0,
  `metakey` text NOT NULL,
  `metadesc` text NOT NULL,
  `metaauthor` text NOT NULL,
  `metarobots` text NOT NULL,
  PRIMARY KEY  (`id_tmp`)
);

CREATE TABLE IF NOT EXISTS `#__xgallery_categories_tmp` (
  `id_tmp` int(11) NOT NULL auto_increment,
  `id` int(11) NOT NULL default '0',
  `pid` int(11) NOT NULL default '0',
  `name` varchar(255) NOT NULL,
  `thumb` text,
  `hits` int(11) NOT NULL default '0',
  `banner` text,
  `quicktake` text NOT NULL,
  `description` text NOT NULL,
  `lft` int(11) NOT NULL default '0',
  `rgt` int(11) NOT NULL default '0',
  `access` int(11) unsigned NOT NULL default '0',
  `groupname` varchar(255) NOT NULL default 'Public',
  `creation_date` datetime NOT NULL,
  `creation_date_tmp` datetime NOT NULL,
  `published` tinyint(1) NOT NULL default 0,
  `metakey` text NOT NULL,
  `metadesc` text NOT NULL,
  `metaauthor` text NOT NULL,
  `metarobots` text NOT NULL,
  PRIMARY KEY  (`id_tmp`)
);